### ISSUE TITLE
Check availability in multiple calendars

### ISSUE THREAD

**Issue by Nevon** [calendso/calendso#15]
I offer "office hours" to my Github sponsors, and would love to use Calendso for booking. One necessarily feature for this use-case, that Calendly does not offer in its free tier, is to check availability across multiple calendars.

That is, I have a work calendar and a personal calendar. I want to book the event in my personal calendar, but I want to make sure that there isn't already something booked in either my personal or my work calendar.

**Comment by clementgalopin** [comment]
I upvote this a lot, this is a very common need

**Comment by ianhyzy** [comment]
I'd contribute to a bountysource for this 💰 multiple google calendars is the killer feature

**Comment by ckorhonen** [comment]
Also would be interested in this feature in the context of meetings with multiple people - I'd want to only show times which work for all participants.

**Comment by jonathan-chin** [comment]
I run a small business and this would be greatly appreciated!

**Comment by glnarayanan** [comment]
A much-needed feature! Multiple Google + Office 365 calendars are much needed. At the very least, multiple Google calendars (which includes G Suite).

**Comment by jfernandogt** [comment]
I made a PR to verifying the busy status in more than one calendar.

**Comment by clementgalopin** [comment]
Hi there, posting this here too because I never got an answer and this PR is causing issues.

I am not sure to understand how does the feature work. It looks like it takes all busy slots from all the calendar that are shared with the main one.

But I do think you would rather need to select which ones of those calendars you want to consider (or not).

Indeed, it is very common to share several secondary calendars with your main one, but it is also very common that other people share their calendar with you so that you can see when they are available or not.

From what I understand, this feature would prevent people from booking your calendar whenever one of your coworker already has an event. This sounds like a big issue for me.

As a reference, you can have a look at how mixmax deals with this issue. They ask you which ones of the shared calendars do you want to take into account.

**Comment by sam-rise** [comment]
Hi there! Unsure whether this is accounted for in this use case above or not, but the biggest blocker to us being able to adopt Calendso and finally ditch Calendly is being able to programmatically check availability/capacity of multiple calendars **across different users**.

Use Case:
We work with and manage tutors and need to find out whether there is capacity across multiple tutors to determine whether we have capacity. It would be an absolute game changer to be able to understand capacity. This would help us understand when our supply of tutors is especially low, so that we can know to bring more on. Currently we are blind to this (except through finicky workarounds).

**Comment by ConnorGargano** [comment]
Hi @Nevon,
You are now able to check availability across multiple calendars as long as they are connected and are selected within your integrations settings.
More information can be found here: https://docs.cal.com/docs/integrations/manage-integrations/manage-calendars
-Thanks Connor
