### ISSUE TITLE
Incorrect timezone when using "Add to your calendar"

### ISSUE THREAD

**Issue by jimafisk** [calendso/calendso#225]
### Issue Summary

If you click on the Google "G" icon in the "Add to your calendar" section of the booking confirmation page, it adds an event to your calendar in the wrong timezone.

There's a conversation with some examples here: https://github.com/calendso/calendso/issues/17#issuecomment-837160227. I just figured this was worth opening as a separate ticket since the original intent of that ticket was for general timezone support, which has been added, and that ticket is closed, which makes it easy to fall through the cracks.

### Steps to Reproduce
1. As a requester, select and date and pick a timezone
2. Fill out your info and press "confirm"
3. At the bottom of the "Booking confirmed" screen click the "G" icon
4. The event that is added in Google Calendar has the incorrect time selected

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I'm curious about the intent of the "Add to your calendar" functionality in general. It appears that an event (in the correct timezone) is already being added to the requester's calendar based on the email address they enter in step 2 above. Is this functionality provided to give the requester an option to add this event to a different calendar? I could see that being helpful, just need to fix the timezone discrepancy or this will likely lead to confusion. Thanks!

**Comment by emrysal** [comment]
I traced the origin of this bug to be an issue taking the UTC date query param, casting it to local time, then feeding it into the button URL as a casted UTC string; which was then taken by google calendar and made calendar time again.

PR opened that fixes this;

> I'm curious about the intent of the "Add to your calendar" functionality in general. It appears that an event (in the correct timezone) is already being added to the requester's calendar based on the email address they enter in step 2 above. Is this functionality provided to give the requester an option to add this event to a different calendar? I could see that being helpful, just need to fix the timezone discrepancy or this will likely lead to confusion. Thanks!

When you have the Gmail calendar integration a Calendar event is created and the requester / invitee is added to the invite automatically. Due to the way Gmail works the event notification is then send to the requester that automatically creates a calendar event on the requester side.

This may or may not be the case for other clients, I am only scratching the surface in many, many tests. However, it is safe to assume that many clients are unable or unwilling to automatically add the event to the user Calendar, this is where this view helps out, giving multiple (ultimately all, with ICS support) download options. 

As more calendar integrations / email notifications are being introduced (email notifications have only recently been built and are very much in early stages) this view continues to provide many ways of adding calendar items directly into the calendar. This is the purpose.
