### ISSUE TITLE
The webpage doesn't handle 500 errors from the API

### ISSUE THREAD

**Issue by rberrelleza** [calendso/calendso#238]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When the API returns a 500 error, the "event calendar" page doesn't handle the error. Instead, it keeps 'loading' forever.

![image](https://user-images.githubusercontent.com/475313/120760457-fce06600-c4c8-11eb-9092-d4f4e94c8a71.png)

(the 500 was due to a configuration issue with my google oauth app it seems)

### Technical details
* Browser version: chrome
* Node.js version: 14
* Anything else that you think could be an issue.

**Comment by baileypumfleet** [comment]
This shows as loading because at the start of the code, we tell the UI to show the loading spinner, and as the code errors out, we don't execute the line of code that stops the spinner.

This will just need to be a try catch or something that checks that an integration is added and show an appropriate error dependent on that.

**Comment by baileypumfleet** [comment]
The app now displays a proper error when we receive an error from the API call
