### ISSUE TITLE
Timezone on Event Level is being ignored

### ISSUE THREAD

**Issue by manuelbiermann** [calendso/calendso#347]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
A summary of the issue. This needs to be a clear detailed-rich summary. 

The Timezone input on the edit event page seems to be ignored and the Timezone set on a user level seems to be used.

### Steps to Reproduce
1. Create a new event
2. Edit the event and change the availability including the Timezone
3. Check the availability/booking page and switch between Timezones

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: https://www.whatsmybrowser.org/b/EN0GT

**Comment by emrysal** [comment]
I'm investigating this at the moment and can verify this happens; but on the <AvailableSlots> component. The Calendar adheres to the event timezone and dates do get shifted. But this causes a spinner during the day shifted because AvailableSlots did not shift. PR incoming with the fix.

![image](https://user-images.githubusercontent.com/1046695/124985968-f77bbb80-e032-11eb-84d3-801b0e6ba425.png)
