### ISSUE TITLE
Multiple availability slots

### ISSUE THREAD

**Issue by carl0s** [calendso/calendso#78]
Hello and first things first, thanks for this!

I'm a heavy user of calendly and one things I love so much are availability schedules.
I think is a must have with calendso as well. Pretty happy to help testing or brainstorming it, and adopting it in my company!

**Comment by baileypumfleet** [comment]
Best way to go about this now is set the start and end of your day on Calendso, and then block the rest of it out on your Google Calendar. We will be implementing multiple availability schedules, but that’s a good workaround for now.

**Comment by carl0s** [comment]
Well yes and no. 
My use case would be: I'd be using calendso for public/prospect meetings and the availability doesn't coincide with being busy per se. It's just windows available for people, while my teams could book me internally. I thought of your workaround but it's a little clunky in my case. Very much looking forward to it!

**Comment by jimafisk** [comment]
It would be great if the availability settings were tied to the Event Type rather than being applied across all calendars. For example I might want to make "office hours" only available from 10am - 2pm on Mon and Tues, but provide "private lessons" anytime 9am - 5pm Mon - Fri.

**Comment by hedwardd** [comment]
@baileypumfleet I would like to tackle this one but have a few concerns (and also want to make sure no one is working on it already)

My plan would be to:
1. Move (or at least add) startTime and endTime to the event objects. This way they can be configured on an event-by-event basis. It just adding, the user could still set their "default" availability on an account level and the event could default to that and then be changed.

2. Add a field(s) to track which days are available. This could be an array of strings (e.g., `["Monday", "Tuesday", "Friday"]`), individual fields (e.g., `allowMonday: true`, `allowTuesday: true`, `allowWednesday: false`...), or possibly even have `startTime` and `endTime` for each weekday (e.g., `mondayStartTime: 600`).

3. Update the event page to start querying available times against event availability.

4. Update the account configuration UI (to set defaults) and then the event configuration UI to show checkboxes and/or number inputs for each day. I'm a bit concerned that updating the current UI with these changes might make it wonky, which is why I wanted to run this by you.

Thoughts?

**Comment by hedwardd** [comment]
@baileypumfleet any feedback or updates on this?

**Comment by emrysal** [comment]
@hedwardd Keep an eye out on today's PRs :) - bit of a preview:

![image](https://user-images.githubusercontent.com/1046695/122191265-7d6c7280-ce8a-11eb-8ca2-27b9e8fbd391.png)

**Comment by emrysal** [comment]
See a WIP branch - I need to finish testing it & sort the integration with the booking UI. It's not quite to the standard I would like it to be upon PR though (but I can't quite put my finger on it tonight).

https://github.com/emrysal/calendso/tree/feature/scheduling

WIP for today, but the configuration part works.

**Comment by emrysal** [comment]
Hi @hedwardd & everyone - this work has now concluded; it took a bit longer than expected as I needed to rework pretty much all of the slot logic. 

I've created a Loom video to demonstrate the options available now which can be found here:
https://www.loom.com/share/e1ef9b4ca0a740809f8a961a79c1aab3

Closing this 👍

**Comment by hedwardd** [comment]
That is awesome @emrysal ! I can't wait to play around with it. With this feature, I think I'll be ready to switch over from calendly for good 👍
